Repository f-lab-edu/jagoga, pull requests merged in 2021-08, with the labels that each got.

#2 [#1] 프로젝트 초기 셋팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/project/jagoga/JagogaApplication.java
  src/main/resources/application.properties
  src/test/java/com/project/jagoga/JagogaApplicationTests.java
Labels: chore

#4 [#3] Github Actions 사용하기
  .github/workflows/main.yml
Labels: chore

#10 [#9] 예외 일괄 처리 기능 추가
  build.gradle
  src/main/java/com/project/jagoga/exception/dto/ValidationErrorResponse.java
Labels: feature

#11 [#7] 회원가입
  build.gradle
  src/main/java/com/project/jagoga/exception/user/DuplicatedUserException.java
  src/main/java/com/project/jagoga/user/application/UserService.java
  src/main/java/com/project/jagoga/user/application/impl/UserServiceImpl.java
  src/main/java/com/project/jagoga/user/domain/PasswordEncoder.java
  src/main/java/com/project/jagoga/user/domain/User.java
  src/main/java/com/project/jagoga/user/domain/UserRepository.java
  src/main/java/com/project/jagoga/user/infrastructure/BCryptPasswordEncoder.java
  src/main/java/com/project/jagoga/user/infrastructure/MemoryUserRepository.java
  src/main/java/com/project/jagoga/user/presentation/controller/UserController.java
  src/main/java/com/project/jagoga/user/presentation/controller/UserExceptionHandler.java
  src/main/java/com/project/jagoga/user/presentation/dto/request/UserCreateRequestDto.java
  src/main/java/com/project/jagoga/user/presentation/dto/response/UserResponseDto.java
  src/test/java/com/project/jagoga/user/application/impl/UserServiceImplTest.java
  src/test/java/com/project/jagoga/user/domain/UserTest.java
  src/test/java/com/project/jagoga/user/infrastructure/BCryptPasswordEncoderTest.java
  src/test/java/com/project/jagoga/user/infrastructure/MemoryUserRepositoryTest.java
Labels: feature

#12 [#8] 상품 생성, 삭제하기
  build.gradle
  src/main/java/com/project/jagoga/accommodation/application/AccommodationService.java
  src/main/java/com/project/jagoga/accommodation/domain/Accommodation.java
  src/main/java/com/project/jagoga/accommodation/domain/AccommodationRepository.java
  src/main/java/com/project/jagoga/accommodation/domain/AccommodationType.java
  src/main/java/com/project/jagoga/accommodation/domain/Address.java
  src/main/java/com/project/jagoga/accommodation/domain/grade/Grade.java
  src/main/java/com/project/jagoga/accommodation/domain/grade/HotelGrade.java
  src/main/java/com/project/jagoga/accommodation/infrastructure/MemoryAccommodationRepository.java
  src/main/java/com/project/jagoga/accommodation/presentation/AccommodationController.java
  src/main/java/com/project/jagoga/accommodation/presentation/dto/AccommodationRequestDto.java
  src/main/java/com/project/jagoga/accommodation/presentation/dto/AccommodationResponseDto.java
  src/main/java/com/project/jagoga/exception/accommodation/DuplicatedAccommodationException.java
  src/main/java/com/project/jagoga/exception/accommodation/NotExistAccommodationException.java
  src/test/java/com/project/jagoga/accommodation/application/AccommodationServiceTest.java
  src/test/java/com/project/jagoga/common/factory/AccommodationFactory.java
  src/test/java/com/project/jagoga/common/factory/MockAccommodation.java
Labels: feature

#16 [#15] ApiResponse 클래스 생성
  src/main/java/com/project/jagoga/exception/dto/ApiResponse.java
  src/main/java/com/project/jagoga/exception/dto/ValidationErrorResponse.java
  src/main/java/com/project/jagoga/user/presentation/controller/UserExceptionHandler.java
Labels: feature

#19 [#14] 숙소 수정 기능 구현
  src/main/java/com/project/jagoga/accommodation/application/AccommodationService.java
  src/main/java/com/project/jagoga/accommodation/domain/Accommodation.java
  src/main/java/com/project/jagoga/accommodation/domain/AccommodationRepository.java
  src/main/java/com/project/jagoga/accommodation/infrastructure/MemoryAccommodationRepository.java
  src/main/java/com/project/jagoga/accommodation/presentation/AccommodationController.java
  src/main/java/com/project/jagoga/exception/accommodation/NotExistAccommodationException.java
  src/test/java/com/project/jagoga/accommodation/application/AccommodationServiceTest.java
  src/test/java/com/project/jagoga/common/factory/AccommodationFactory.java
Labels: feature

#23 [#20] 숙소 등록, 수정 시 유효성 검사 기능
  src/main/java/com/project/jagoga/accommodation/domain/AccommodationType.java
  src/main/java/com/project/jagoga/accommodation/presentation/controller/AccommodationController.java
  src/main/java/com/project/jagoga/accommodation/presentation/controller/AccommodationExceptionHandler.java
  src/main/java/com/project/jagoga/accommodation/presentation/dto/AccommodationRequestDto.java
  src/main/java/com/project/jagoga/exception/accommodation/NotFoundAccommodationTypeException.java
  src/test/java/com/project/jagoga/common/factory/AccommodationFactory.java
Labels: feature

#22 [#21] 로그인 검증
  src/main/java/com/project/jagoga/exception/user/ExpiredTokenException.java
  src/main/java/com/project/jagoga/exception/user/UnAuthorizedException.java
  src/main/java/com/project/jagoga/global/config/WebConfig.java
  src/main/java/com/project/jagoga/user/domain/Authentication.java
  src/main/java/com/project/jagoga/user/domain/LoginCheck.java
  src/main/java/com/project/jagoga/user/infrastructure/JwtTokenAuthentication.java
  src/main/java/com/project/jagoga/user/presentation/interceptor/AuthenticationInterceptor.java
  src/test/java/com/project/jagoga/user/infrastructure/JwtTokenAuthenticationTest.java
  src/test/java/com/project/jagoga/user/presentation/controller/UserControllerTest.java
Labels: feature

#28 [#24] 주소 도메인 구현
  src/main/java/com/project/jagoga/accommodation/application/AccommodationService.java
  src/main/java/com/project/jagoga/accommodation/domain/Accommodation.java
  src/main/java/com/project/jagoga/accommodation/domain/AccommodationRepository.java
  src/main/java/com/project/jagoga/accommodation/domain/AccommodationType.java
  src/main/java/com/project/jagoga/accommodation/domain/Address.java
  src/main/java/com/project/jagoga/accommodation/domain/address/Category.java
  src/main/java/com/project/jagoga/accommodation/domain/address/City.java
  src/main/java/com/project/jagoga/accommodation/domain/address/State.java
  src/main/java/com/project/jagoga/accommodation/infrastructure/MemoryAccommodationRepository.java
  src/main/java/com/project/jagoga/accommodation/presentation/controller/AccommodationController.java
  src/main/java/com/project/jagoga/accommodation/presentation/controller/AccommodationExceptionHandler.java
  src/main/java/com/project/jagoga/accommodation/presentation/dto/AccommodationRequestDto.java
  src/main/java/com/project/jagoga/accommodation/presentation/dto/AccommodationResponseDto.java
  src/main/java/com/project/jagoga/exception/accommodation/UnknownAccommodationTypeException.java
  src/test/java/com/project/jagoga/common/factory/AccommodationFactory.java
  src/test/java/com/project/jagoga/common/factory/MockAccommodation.java
Labels: feature

#29 [#25] User 권한(Role) 추가
  src/main/java/com/project/jagoga/exception/user/ForbiddenException.java
  src/main/java/com/project/jagoga/exception/user/UnknownRoleTypeException.java
  src/main/java/com/project/jagoga/global/config/WebConfig.java
  src/main/java/com/project/jagoga/user/application/UserService.java
  src/main/java/com/project/jagoga/user/application/impl/UserServiceImpl.java
  src/main/java/com/project/jagoga/user/domain/AuthUser.java
  src/main/java/com/project/jagoga/user/domain/Authentication.java
  src/main/java/com/project/jagoga/user/domain/LoginCheck.java
  src/main/java/com/project/jagoga/user/domain/RequireLoginUser.java
  src/main/java/com/project/jagoga/user/domain/Role.java
  src/main/java/com/project/jagoga/user/domain/User.java
  src/main/java/com/project/jagoga/user/infrastructure/JwtTokenAuthentication.java
  src/main/java/com/project/jagoga/user/presentation/controller/UserController.java
  src/main/java/com/project/jagoga/user/presentation/controller/UserExceptionHandler.java
  src/main/java/com/project/jagoga/user/presentation/dto/request/UserCreateRequestDto.java
  src/main/java/com/project/jagoga/user/presentation/dto/response/UserResponseDto.java
  src/main/java/com/project/jagoga/user/presentation/resolver/RequireLoginUserArgumentResolver.java
  src/test/java/com/project/jagoga/user/application/impl/UserServiceImplTest.java
Labels: feature

#34 [#33] checkstyle에 맞게 code 수정
  src/main/java/com/project/jagoga/user/application/impl/UserServiceImpl.java
  src/main/java/com/project/jagoga/user/presentation/controller/UserController.java
  src/main/java/com/project/jagoga/user/presentation/controller/UserExceptionHandler.java
  src/main/java/com/project/jagoga/user/presentation/resolver/RequireLoginUserArgumentResolver.java
Labels: bug
