Repository f-lab-edu/jagoga, pull requests merged in 2021-09, with the labels that each got.

#35 [#31] Accommodation에 User 권한(Role) 추가
  config/checkstyle/naver-checkstyle-rules.xml
  naver-checkstyle-rules.xml
  src/main/java/com/project/jagoga/accommodation/application/AccommodationService.java
  src/main/java/com/project/jagoga/accommodation/domain/Accommodation.java
  src/main/java/com/project/jagoga/accommodation/presentation/controller/AccommodationController.java
  src/main/java/com/project/jagoga/accommodation/presentation/dto/AccommodationRequestDto.java
  src/main/java/com/project/jagoga/user/application/impl/UserServiceImpl.java
  src/main/java/com/project/jagoga/utils/VerificationUtils.java
  src/test/java/com/project/jagoga/accommodation/application/AccommodationServiceTest.java
  src/test/java/com/project/jagoga/common/factory/AccommodationFactory.java
  src/test/java/com/project/jagoga/common/factory/MockAccommodation.java
Labels: feature

#38 [#36] Accommodation 도메인 테스트
  src/main/java/com/project/jagoga/accommodation/presentation/dto/AccommodationRequestDto.java
  src/main/java/com/project/jagoga/user/presentation/controller/UserExceptionHandler.java
  src/test/java/com/project/jagoga/accommodation/application/AccommodationServiceTest.java
  src/test/java/com/project/jagoga/accommodation/presentation/controller/AccommodationControllerTest.java
  src/test/java/com/project/jagoga/common/factory/AccommodationFactory.java
Labels: test

#41 config: githuba action 수정
  .github/workflows/main.yml
Labels: chore

#42 config: github action mysql 순서 수정
  .github/workflows/main.yml
Labels: chore

#46 [#45] flyway 의존성 및 스크립트 파일 추가
  build.gradle
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__empty.sql
Labels: chore

#48 Update README.md
  README.md
Labels: docs

#51 [#50] 데이터베이스 users 테이블 제약조건 추가
  build.gradle
  sql/users.sql
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__base.sql
  src/main/resources/db/migration/V1__empty.sql
  src/test/resources/application.yml
Labels: refactor

#54 [#52] roomType 등록 기능
  src/main/java/com/project/jagoga/exception/roomtype/NotExistRoomTypeException.java
  src/main/java/com/project/jagoga/roomtype/application/RoomTypeService.java
  src/main/java/com/project/jagoga/roomtype/domain/RoomType.java
  src/main/java/com/project/jagoga/roomtype/domain/RoomTypeRepository.java
  src/main/java/com/project/jagoga/roomtype/presentation/controller/RoomTypeController.java
  src/main/java/com/project/jagoga/roomtype/presentation/controller/RoomTypeExceptionHandler.java
  src/main/java/com/project/jagoga/roomtype/presentation/dto/RoomTypeCreateRequestDto.java
  src/main/java/com/project/jagoga/roomtype/presentation/dto/RoomTypeResponseDto.java
  src/main/resources/db/migration/V2__roomtype.sql
  src/test/java/com/project/jagoga/roomtype/application/RoomTypeServiceTest.java
Labels: feature

#57 [#56] roomType 등록 기능 수정
  src/main/java/com/project/jagoga/roomtype/application/RoomTypeService.java
  src/main/java/com/project/jagoga/roomtype/domain/RoomType.java
  src/main/java/com/project/jagoga/roomtype/presentation/controller/RoomTypeController.java
  src/main/java/com/project/jagoga/roomtype/presentation/dto/RoomTypeCreateRequestDto.java
  src/main/java/com/project/jagoga/roomtype/presentation/dto/RoomTypeResponseDto.java
  src/main/resources/db/migration/V3__roomtype_add_price_column.sql
  src/test/java/com/project/jagoga/roomtype/application/RoomTypeServiceTest.java
Labels: refactor
